@host = http://localhost:3000/api/users
@host/info = http://localhost:3000/api/users/me


### Sign-Up
POST {{host}}/signup 
Content-Type: application/json

{
  "name": "테스트",
  "email": "test36@naver.com",
  "password": "123123",
  "confirmPassword": "123123",
  "phone":"1231234",
  "address":"123123123/123123"

}


### Sign-In
POST {{host}}/signin
Content-Type: application/json

{
  "email": "test36@naver.com",
  "password": "123123"
}

### getMyInfo
GET {{host/info}}
Content-Type: application/json


### UpdateMyInfo
PUT {{host}}
Content-Type: application/json
{
  "phone": "010-5939-2121", 
  "address":"강남구 강남시 강남도"
}


## DeleteMyInfo
DELETE {{host}} 
Content-Type: application/json
